import assert from 'node:assert/strict';
import { planRoute } from '../lib/planner.mjs';
const catalog = { 'anthropic-messages': { old: { id: 'old', name: 'Old', api: 'anthropic-messages', baseUrl: 'https://a',
  contextWindow: 262144, maxTokens: 65536, input: ['text', 'image'], reasoning: true } } };
const md = (id, context = 8192, output = 1024) => ({ id, limit: { context, output }, modalities: { input: ['text'], output: ['text'] } });
const official = (ids, complete = false, models = {}) => ({ ids: new Set(ids), complete, models });
const plan = (overrides = {}) => planRoute({ route: 'test', catalog, settings: {}, ...overrides });
let p = plan({ metadata: { old: md('old') }, source: 'pi-ai' });
assert.equal(p.models[0].contextWindow, 262144);
assert.deepEqual(p.models[0].input, ['text', 'image']);
assert.equal(p.models[0].reasoning, true);
assert.deepEqual(p.diff.updated, []);
p = plan({ official: official(['old', 'new'], false, { new: md('new') }) });
assert.equal(p.additions[0].group, 'anthropic-messages');
assert.equal(p.additions[0].entry.baseUrl, 'https://a');
assert.deepEqual(p.officialAdded, ['new'], 'official works without any third-party source');
p = plan({ metadata: { new: { id: 'new' } }, official: official(['new', 'old'], false, { new: md('new') }) });
assert.equal(p.additions.length, 1, 'incomplete third-party object must not block official fields');
p = plan({ official: official(['new', 'old']) });
assert.equal(p.additions.length, 0);
assert.match(p.pending[0].reason, /容量|类型/);
p = plan({ source: 'unknown', metadata: { ghost: md('ghost') }, officialConfigured: true });
assert.equal(p.additions.length, 0);
assert.equal(p.pending.length, 1);
p = plan({ source: 'models.dev', metadata: { ghost: md('ghost') }, official: official(['old']) });
assert.deepEqual(p.diff.unverified, ['ghost']);
p = plan({ source: 'models.dev', metadata: { allowed: md('ghost') } });
assert.equal(p.additions.length, 0);
assert.equal(p.warnings.length > 0, true);
const full = official(['other'], true);
p = plan({ official: full, now: 0, settings: { removeStale: true } });
assert.deepEqual(p.removals, []);
const previous = { missing: p.missing };
p = plan({ official: full, previous, now: 25 * 3600_000, settings: { removeStale: true } });
assert.deepEqual(p.removals, ['old']);
p = plan({ official: full, previous, now: 25 * 3600_000, settings: { removeStale: true }, routeConfig: { keep: ['old'] } });
assert.deepEqual(p.removals, []);
p = plan({ official: official(['other'], false), previous, now: 25 * 3600_000, settings: { removeStale: true } });
assert.deepEqual(p.removals, []);
assert.deepEqual(Object.keys(p.missing), []);
p = plan({ previous, now: 25 * 3600_000, settings: { removeStale: true } });
assert.deepEqual(p.removals, []);
p = plan({ official: official(['org/old'], true), previous, now: 25 * 3600_000, settings: { removeStale: true } });
assert.deepEqual(p.removals, [], 'namespace safeguard protects output and catalog together');
const multi = structuredClone(catalog);
multi['openai-completions'] = { other: { ...catalog['anthropic-messages'].old, id: 'other', api: 'openai-completions', baseUrl: 'https://b' } };
p = plan({ catalog: multi, official: official(['new'], false, { new: md('new') }) });
assert.equal(p.additions.length, 0);
assert.match(p.pending[0].reason, /协议/);
p = plan({ official: official(['new'], false, { new: { ...md('new'), modalities: { output: ['audio'] } } }) });
assert.match(p.pending[0].reason, /非聊天/);
assert.throws(() => plan({ catalog: { bad: [] } }), /bucket/);
p = plan({ official: official(['old'], false, { old: md('old', 100, 1000) }) });
assert.equal(p.models[0].contextWindow, 262144);
assert.equal(p.models[0].maxTokens, 65536, 'invalid official capacity pair must not corrupt existing entry');
p = plan({ official: official(['old', 'embed'], false, { embed: { ...md('embed'), mode: 'embedding' } }) });
assert.equal(p.additions.length, 0);
assert.match(p.pending[0].reason, /非聊天/);
p = plan({ official: official(['old', 'unknown'], false, { unknown: { id: 'unknown', limit: { context: 8192, output: 1024 } } }) });
assert.equal(p.additions.length, 0, 'capacity and ID alone do not prove chat type');
assert.match(p.pending[0].reason, /类型/);
p = plan({ official: official(['old', 'unknown'], false, { unknown: { id: 'unknown', limit: { context: 8192, output: 1024 } } }), officialConfig: { assumeChat: true } });
assert.equal(p.additions.length, 1, 'explicit user confirmation may supply unknown chat type');
console.log('PLANNER TESTS PASSED');
